export const tableData = [
  {
    id: 1,
    age: 82,
    first_name: "Dorelle",
    last_name: "Harling",
    email: "dharling0@rediff.com",
    gender: "Female",
    phone: "232(152)707-0110",
    ccupation: "Financial Advisor",
    img: "/assets/images/users/user-1.jpg",
  },
  {
    id: 2,
    age: 89,
    first_name: "Bendicty",
    last_name: "Llewellin",
    email: "bllewellin1@example.com",
    gender: "Male",
    phone: "420(169)218-1769",
    ccupation: "Marketing Assistant",
    img: "/assets/images/users/user-2.jpg",
  },
  {
    id: 3,
    age: 28,
    first_name: "Remy",
    last_name: "Carbry",
    email: "rcarbry2@prlog.org",
    gender: "Polygender",
    phone: "86(958)204-4491",
    ccupation: "Mechanical Systems Engineer",
    img: "/assets/images/users/user-3.jpg",
  },
  {
    id: 4,
    age: 20,
    first_name: "Bernardo",
    last_name: "Hacun",
    email: "bhacun3@xinhuanet.com",
    gender: "Male",
    phone: "86(974)709-5254",
    ccupation: "Research Assistant IV",
    img: "/assets/images/users/user-4.jpg",
  },
  {
    id: 5,
    age: 2,
    first_name: "Emelia",
    last_name: "Garstang",
    email: "egarstang4@miitbeian.gov.cn",
    gender: "Female",
    phone: "55(644)175-6748",
    ccupation: "Business Systems Development Analyst",
    img: "/assets/images/users/user-5.jpg",
  },
  // {
  //   id: 6,
  //   age: 98,
  //   first_name: "Dian",
  //   last_name: "Dopson",
  //   email: "ddopson5@examiner.com",
  //   gender: "Female",
  //   phone: "51(186)560-8480",
  //   ccupation: "Cost Accountant",
  //   img: "/assets/images/users/user-6.jpg",
  // },
  // {
  //   id: 7,
  //   age: 17,
  //   first_name: "Coretta",
  //   last_name: "Ponter",
  //   email: "cponter6@loc.gov",
  //   gender: "Female",
  //   phone: "1(941)734-6255",
  //   ccupation: "Budget/Accounting Analyst II",
  //   img: "/assets/images/users/user-1.jpg",
  // },
  // {
  //   id: 8,
  //   age: 85,
  //   first_name: "Valentine",
  //   last_name: "Crispin",
  //   email: "vcrispin7@dailymotion.com",
  //   gender: "Male",
  //   phone: "380(627)884-8734",
  //   ccupation: "Project Manager",
  //   img: "/assets/images/users/user-2.jpg",
  // },
  // {
  //   id: 9,
  //   age: 77,
  //   first_name: "Gill",
  //   last_name: "Sutlieff",
  //   email: "gsutlieff8@engadget.com",
  //   gender: "Male",
  //   phone: "386(374)937-6305",
  //   ccupation: "Recruiter",
  //   img: "/assets/images/users/user-3.jpg",
  // },
  // {
  //   id: 10,
  //   age: 23,
  //   first_name: "Noreen",
  //   last_name: "Blick",
  //   email: "nblick9@usa.gov",
  //   gender: "Female",
  //   phone: "998(884)893-6477",
  //   ccupation: "Human Resources Manager",
  //   img: "/assets/images/users/user-4.jpg",
  // },
  // {
  //   id: 11,
  //   age: 2,
  //   first_name: "Noll",
  //   last_name: "Doniso",
  //   email: "ndonisoa@dropbox.com",
  //   gender: "Male",
  //   phone: "62(891)114-3443",
  //   ccupation: "General Manager",
  //   img: "/assets/images/users/user-5.jpg",
  // },
  // {
  //   id: 12,
  //   age: 3,
  //   first_name: "Edvard",
  //   last_name: "Espinas",
  //   email: "eespinasb@over-blog.com",
  //   gender: "Male",
  //   phone: "62(564)280-1360",
  //   ccupation: "Senior Financial Analyst",
  //   img: "/assets/images/users/user-6.jpg",
  // },
  // {
  //   id: 13,
  //   age: 66,
  //   first_name: "Nicolis",
  //   last_name: "Aglione",
  //   email: "naglionec@epa.gov",
  //   gender: "Male",
  //   phone: "57(354)171-9855",
  //   ccupation: "Senior Financial Analyst",
  //   img: "/assets/images/users/user-1.jpg",
  // },
  // {
  //   id: 14,
  //   age: 2,
  //   first_name: "Natalee",
  //   last_name: "Mabbs",
  //   email: "nmabbsd@elegantthemes.com",
  //   gender: "Female",
  //   phone: "63(963)373-2874",
  //   ccupation: "Operator",
  //   img: "/assets/images/users/user-2.jpg",
  // },
  // {
  //   id: 15,
  //   age: 95,
  //   first_name: "Uri",
  //   last_name: "Bramford",
  //   email: "ubramforde@seesaa.net",
  //   gender: "Male",
  //   phone: "55(546)435-7304",
  //   ccupation: "Programmer II",
  //   img: "/assets/images/users/user-3.jpg",
  // },
  // {
  //   id: 16,
  //   age: 58,
  //   first_name: "Emmy",
  //   last_name: "Garm",
  //   email: "egarmf@engadget.com",
  //   gender: "Female",
  //   phone: "591(180)907-2249",
  //   ccupation: "Account Executive",
  //   img: "/assets/images/users/user-4.jpg",
  // },
  // {
  //   id: 17,
  //   age: 86,
  //   first_name: "Hoyt",
  //   last_name: "Runnalls",
  //   email: "hrunnallsg@dailymotion.com",
  //   gender: "Male",
  //   phone: "30(515)278-6344",
  //   ccupation: "Budget/Accounting Analyst II",
  //   img: "/assets/images/users/user-5.jpg",
  // },
  // {
  //   id: 18,
  //   age: 60,
  //   first_name: "Marillin",
  //   last_name: "Maryet",
  //   email: "mmaryeth@dagondesign.com",
  //   gender: "Female",
  //   phone: "27(660)562-5635",
  //   ccupation: "Junior Executive",
  //   img: "/assets/images/users/user-6.jpg",
  // },
  // {
  //   id: 19,
  //   age: 16,
  //   first_name: "Raddy",
  //   last_name: "Cretney",
  //   email: "rcretneyi@cmu.edu",
  //   gender: "Male",
  //   phone: "374(646)574-6654",
  //   ccupation: "Chemical Engineer",
  //   img: "/assets/images/users/user-1.jpg",
  // },
  // {
  //   id: 20,
  //   age: 42,
  //   first_name: "Decca",
  //   last_name: "Narup",
  //   email: "dnarupj@dagondesign.com",
  //   gender: "Male",
  //   phone: "7(964)301-2278",
  //   ccupation: "Nurse Practicioner",
  //   img: "/assets/images/users/user-2.jpg",
  // },
  // {
  //   id: 21,
  //   age: 27,
  //   first_name: "Orion",
  //   last_name: "Dunne",
  //   email: "odunnek@cnbc.com",
  //   gender: "Male",
  //   phone: "1(910)450-9780",
  //   ccupation: "Data Coordiator",
  //   img: "/assets/images/users/user-3.jpg",
  // },
  // {
  //   id: 22,
  //   age: 47,
  //   first_name: "Jeanie",
  //   last_name: "Nozzolii",
  //   email: "jnozzoliil@stumbleupon.com",
  //   gender: "Female",
  //   phone: "62(567)910-7256",
  //   ccupation: "Registered Nurse",
  //   img: "/assets/images/users/user-4.jpg",
  // },
  // {
  //   id: 23,
  //   age: 72,
  //   first_name: "Norah",
  //   last_name: "Grivori",
  //   email: "ngrivorim@delicious.com",
  //   gender: "Female",
  //   phone: "7(870)757-4318",
  //   ccupation: "Sales Representative",
  //   img: "/assets/images/users/user-5.jpg",
  // },
  // {
  //   id: 24,
  //   age: 89,
  //   first_name: "Massimiliano",
  //   last_name: "Snodden",
  //   email: "msnoddenn@ucoz.ru",
  //   gender: "Male",
  //   phone: "82(582)574-1970",
  //   ccupation: "Recruiter",
  //   img: "/assets/images/users/user-6.jpg",
  // },
  // {
  //   id: 25,
  //   age: 62,
  //   first_name: "Glori",
  //   last_name: "Nannoni",
  //   email: "gnannonio@ihg.com",
  //   gender: "Female",
  //   phone: "48(356)235-7306",
  //   ccupation: "Senior Sales Associate",
  //   img: "/assets/images/users/user-1.jpg",
  // },
  // {
  //   id: 26,
  //   age: 23,
  //   first_name: "Karly",
  //   last_name: "Janous",
  //   email: "kjanousp@liveinternet.ru",
  //   gender: "Female",
  //   phone: "33(312)747-9116",
  //   ccupation: "Speech Pathologist",
  //   img: "/assets/images/users/user-2.jpg",
  // },
  // {
  //   id: 27,
  //   age: 100,
  //   first_name: "Hugibert",
  //   last_name: "MacAllester",
  //   email: "hmacallesterq@constantcontact.com",
  //   gender: "Male",
  //   phone: "62(416)665-0619",
  //   ccupation: "Account Coordinator",
  //   img: "/assets/images/users/user-3.jpg",
  // },
  // {
  //   id: 28,
  //   age: 85,
  //   first_name: "Marlow",
  //   last_name: "Munsey",
  //   email: "mmunseyr@spiegel.de",
  //   gender: "Male",
  //   phone: "967(713)722-9345",
  //   ccupation: "Senior Editor",
  //   img: "/assets/images/users/user-4.jpg",
  // },
  // {
  //   id: 29,
  //   age: 39,
  //   first_name: "Tuckie",
  //   last_name: "Inwood",
  //   email: "tinwoods@alexa.com",
  //   gender: "Male",
  //   phone: "998(291)785-1422",
  //   ccupation: "Paralegal",
  //   img: "/assets/images/users/user-5.jpg",
  // },
  // {
  //   id: 30,
  //   age: 59,
  //   first_name: "Krishna",
  //   last_name: "Ovendale",
  //   email: "kovendalet@telegraph.co.uk",
  //   gender: "Male",
  //   phone: "81(977)473-0581",
  //   ccupation: "Environmental Specialist",
  //   img: "/assets/images/users/user-6.jpg",
  // },
  // {
  //   id: 31,
  //   age: 43,
  //   first_name: "Wolf",
  //   last_name: "Vannah",
  //   email: "wvannahu@godaddy.com",
  //   gender: "Male",
  //   phone: "48(938)552-5576",
  //   ccupation: "Financial Analyst",
  //   img: "/assets/images/users/user-1.jpg",
  // },
  // {
  //   id: 32,
  //   age: 33,
  //   first_name: "Levy",
  //   last_name: "Staresmeare",
  //   email: "lstaresmearev@eventbrite.com",
  //   gender: "Male",
  //   phone: "66(971)191-0397",
  //   ccupation: "Biostatistician IV",
  //   img: "/assets/images/users/user-2.jpg",
  // },
  // {
  //   id: 33,
  //   age: 30,
  //   first_name: "Odell",
  //   last_name: "Minero",
  //   email: "ominerow@irs.gov",
  //   gender: "Male",
  //   phone: "62(187)718-2690",
  //   ccupation: "Director of Sales",
  //   img: "/assets/images/users/user-3.jpg",
  // },
  // {
  //   id: 34,
  //   age: 16,
  //   first_name: "Gaston",
  //   last_name: "Rudgley",
  //   email: "grudgleyx@mozilla.com",
  //   gender: "Male",
  //   phone: "54(491)426-6076",
  //   ccupation: "Chief Design Engineer",
  //   img: "/assets/images/users/user-4.jpg",
  // },
  // {
  //   id: 35,
  //   age: 55,
  //   first_name: "Wain",
  //   last_name: "Renac",
  //   email: "wrenacy@illinois.edu",
  //   gender: "Male",
  //   phone: "7(719)471-4771",
  //   ccupation: "Database Administrator I",
  //   img: "/assets/images/users/user-5.jpg",
  // },
  // {
  //   id: 36,
  //   age: 46,
  //   first_name: "Timmie",
  //   last_name: "Robotham",
  //   email: "trobothamz@xing.com",
  //   gender: "Male",
  //   phone: "63(132)653-1655",
  //   ccupation: "Recruiting Manager",
  //   img: "/assets/images/users/user-6.jpg",
  // },
  // {
  //   id: 37,
  //   age: 33,
  //   first_name: "Windham",
  //   last_name: "Dudman",
  //   email: "wdudman10@smh.com.au",
  //   gender: "Male",
  //   phone: "86(695)839-0433",
  //   ccupation: "Senior Financial Analyst",
  //   img: "/assets/images/users/user-1.jpg",
  // },
  // {
  //   id: 38,
  //   age: 74,
  //   first_name: "Allene",
  //   last_name: "Noury",
  //   email: "anoury11@soup.io",
  //   gender: "Female",
  //   phone: "351(222)474-2030",
  //   ccupation: "Research Associate",
  //   img: "/assets/images/users/user-2.jpg",
  // },
  // {
  //   id: 39,
  //   age: 16,
  //   first_name: "Cornie",
  //   last_name: "Rozec",
  //   email: "crozec12@howstuffworks.com",
  //   gender: "Male",
  //   phone: "380(481)480-8282",
  //   ccupation: "Chief Design Engineer",
  //   img: "/assets/images/users/user-3.jpg",
  // },
  // {
  //   id: 40,
  //   age: 44,
  //   first_name: "Jeremie",
  //   last_name: "Thynne",
  //   email: "jthynne13@zdnet.com",
  //   gender: "Male",
  //   phone: "251(966)881-4028",
  //   ccupation: "Analog Circuit Design manager",
  //   img: "/assets/images/users/user-4.jpg",
  // },
  // {
  //   id: 41,
  //   age: 59,
  //   first_name: "Erda",
  //   last_name: "Frayne",
  //   email: "efrayne14@moonfruit.com",
  //   gender: "Female",
  //   phone: "86(502)895-4971",
  //   ccupation: "Biostatistician I",
  //   img: "/assets/images/users/user-5.jpg",
  // },
  // {
  //   id: 42,
  //   age: 20,
  //   first_name: "Giulietta",
  //   last_name: "Serrels",
  //   email: "gserrels15@pbs.org",
  //   gender: "Female",
  //   phone: "86(626)869-8255",
  //   ccupation: "Social Worker",
  //   img: "/assets/images/users/user-6.jpg",
  // },
  // {
  //   id: 43,
  //   age: 3,
  //   first_name: "Shaylah",
  //   last_name: "Symones",
  //   email: "ssymones16@indiegogo.com",
  //   gender: "Female",
  //   phone: "353(823)187-8422",
  //   ccupation: "Administrative Assistant I",
  //   img: "/assets/images/users/user-1.jpg",
  // },
  // {
  //   id: 44,
  //   age: 40,
  //   first_name: "Thorvald",
  //   last_name: "Robjant",
  //   email: "trobjant17@mapy.cz",
  //   gender: "Male",
  //   phone: "66(792)606-7511",
  //   ccupation: "Mechanical Systems Engineer",
  //   img: "/assets/images/users/user-2.jpg",
  // },
  // {
  //   id: 45,
  //   age: 41,
  //   first_name: "Pauletta",
  //   last_name: "Horsewood",
  //   email: "phorsewood18@yahoo.co.jp",
  //   gender: "Female",
  //   phone: "62(413)578-6139",
  //   ccupation: "Legal Assistant",
  //   img: "/assets/images/users/user-3.jpg",
  // },
  // {
  //   id: 46,
  //   age: 21,
  //   first_name: "Adan",
  //   last_name: "Nardrup",
  //   email: "anardrup19@discovery.com",
  //   gender: "Female",
  //   phone: "7(731)243-8504",
  //   ccupation: "Office Assistant IV",
  //   img: "/assets/images/users/user-4.jpg",
  // },
  // {
  //   id: 47,
  //   age: 94,
  //   first_name: "Cleopatra",
  //   last_name: "Robens",
  //   email: "crobens1a@bluehost.com",
  //   gender: "Female",
  //   phone: "86(468)199-8951",
  //   ccupation: "Biostatistician I",
  //   img: "/assets/images/users/user-5.jpg",
  // },
  // {
  //   id: 48,
  //   age: 19,
  //   first_name: "Guillemette",
  //   last_name: "Gehring",
  //   email: "ggehring1b@exblog.jp",
  //   gender: "Female",
  //   phone: "385(277)272-7058",
  //   ccupation: "Account Representative IV",
  //   img: "/assets/images/users/user-6.jpg",
  // },
  // {
  //   id: 49,
  //   age: 51,
  //   first_name: "Leora",
  //   last_name: "Maudling",
  //   email: "lmaudling1c@topsy.com",
  //   gender: "Female",
  //   phone: "54(565)109-8803",
  //   ccupation: "Physical Therapy Assistant",
  //   img: "/assets/images/users/user-1.jpg",
  // },
  // {
  //   id: 50,
  //   age: 51,
  //   first_name: "Leora",
  //   last_name: "Maudling",
  //   email: "lmaudling1c@topsy.com",
  //   gender: "Female",
  //   phone: "54(565)109-8803",
  //   ccupation: "Physical Therapy Assistant",
  //   img: "/assets/images/users/user-2.jpg",
  // },
];

export const dashboardTable = [
  {
    id: 1,
    date: "2021-08-01 16:03:50",
    priority: "Tier 3",
    location: "Akins High School",
    title: "Tree Limb Down (0)",
    status: "Open",
    assigned: "Eric Tramer",
    action: ["Details"],
  },
  {
    id: 2,
    date: "2021-08-01 16:33:10",
    priority: "Tier 3",
    location: "Anderson High School",
    title: "Graffiti in Boys Bathroom (2)",
    status: "Open",
    assigned: "Eric Tramer",
    action: ["Details"],
  },
  {
    id: 3,
    date: "2021-08-02 16:03:50",
    priority: "Tier 3",
    location: "Anderson High School",
    title: "Broken Window Front Door (1)",
    status: "Open",
    assigned: "Richard Belding",
    action: ["Details"],
  },
  {
    id: 4,
    date: "2021-08-02 18:07:50",
    priority: "Tier 1",
    location: "Akins High School",
    title: "Graffiti in Girl's Bathroom (1)",
    status: "Pending",
    assigned: "Richard Belding",
    action: ["Details"],
  },
  {
    id: 5,
    date: "2021-08-02 16:07:50",
    priority: "Tier 3",
    location: "Akins High School",
    title: "Broken Ceiling Tile (2)",
    status: "Pending",
    assigned: "Richard Belding",
    action: ["Details"],
  },
];

export const ticketsTable = [
  {
    date: "02-23-2023",
    priority: "Tier 3",
    location: "Akins High School",
    title: "Graffiti in Girl's Bathroom (1)",
    status: "Pending",
    assigned: "Eric Tramer",
    action: ["detail", "address"],
  },
  {
    date: "03-03-2023",
    priority: "Tier 1",
    location: "Akins High School",
    title: "Broken Ceiling Tile (2)",
    status: "Pending",
    assigned: "Eric Tramer",
    action: ["detail", "address"],
  },
  {
    date: "03-03-2023",
    priority: "Tier 3",
    location: "Anderson High School",
    title: "Broken Window Front Door (1)",
    status: "Open",
    assigned: "Richard Belding",
    action: ["detail", "address"],
  },
  {
    date: "08-23-2023",
    priority: "Tier 3",
    location: "Akins High School",
    title: "Graffiti in Girl's Bathroom (1)",
    status: "Assigned",
    assigned: "Richard Belding",
    action: ["detail", "accept", "reject"],
  },
];

export const locationsTable = [
  {
    campus: "Akins High School",
    location: "Admin Building",
    action: ["View"],
  },
  {
    campus: "Akins High School",
    location: "Art Room",
    action: ["View"],
  },
  {
    campus: "Akins High School",
    location: "Band Room",
    action: ["View"],
  },
  {
    campus: "Akins High School",
    location: "Baseball Field",
    action: ["View"],
  },
  {
    campus: "Akins High School",
    location: "Classroom",
    action: ["View"],
  },
  
];

export const customersTable = [
  {
    location: "Admin Building",
    action: ["View"],
  },
  {
    location: "Art Room",
    action: ["View"],
  }, 
];

export const homeTable = [
  {
    company: "/assets/images/users/user-1.jpg",
    category: "Ornamental Railings",
    views: 343,
    revenue: "$231.26",
    sales: 95,
    up: false,
  },
  {
    company: "/assets/images/users/user-2.jpg",
    category: "Asphalt Paving",
    views: 315,
    revenue: "$432.81",
    sales: 197,
    up: false,
  },
  {
    company: "/assets/images/users/user-3.jpg",
    category: "Framing (Steel)",
    views: 329,
    revenue: "$437.65",
    sales: 137,
    up: true,
  },
  {
    company: "/assets/images/users/user-4.jpg",
    category: "Structural and Misc Steel (Fabrication)",
    views: 336,
    revenue: "$387.55",
    sales: 101,
    up: true,
  },
  {
    company: "/assets/images/users/user-5.jpg",
    category: "Wall Protection",
    views: 375,
    revenue: "$489.80",
    sales: 99,
    up: false,
  },
  {
    company: "/assets/images/users/user-6.jpg",
    category: "Marlite Panels (FED)",
    views: 490,
    revenue: "$421.45",
    sales: 101,
    up: true,
  },
  {
    company: "/assets/images/users/user-1.jpg",
    category: "Epoxy Flooring",
    views: 433,
    revenue: "$207.61",
    sales: 197,
    up: false,
  },
  {
    company: "/assets/images/users/user-2.jpg",
    category: "Epoxy Flooring",
    views: 499,
    revenue: "$392.86",
    sales: 91,
    up: false,
  },
  {
    company: "/assets/images/users/user-3.jpg",
    category: "Marlite Panels (FED)",
    views: 441,
    revenue: "$162.87",
    sales: 115,
    up: false,
  },
  {
    company: "/assets/images/users/user-4.jpg",
    category: "RF Shielding",
    views: 415,
    revenue: "$268.58",
    sales: 128,
    up: false,
  },
  {
    company: "/assets/images/users/user-5.jpg",
    category: "Roofing (Metal)",
    views: 303,
    revenue: "$369.19",
    sales: 179,
    up: false,
  },
  {
    company: "/assets/images/users/user-6.jpg",
    category: "RF Shielding",
    views: 415,
    revenue: "$420.87",
    sales: 148,
    up: false,
  },
  {
    company: "/assets/images/users/user-1.jpg",
    category: "Curb & Gutter",
    views: 493,
    revenue: "$420.26",
    sales: 152,
    up: false,
  },
  {
    company: "/assets/images/users/user-2.jpg",
    category: "Structural & Misc Steel Erection",
    views: 498,
    revenue: "$228.41",
    sales: 151,
    up: false,
  },
  {
    company: "/assets/images/users/user-3.jpg",
    category: "Retaining Wall and Brick Pavers",
    views: 465,
    revenue: "$140.83",
    sales: 71,
    up: false,
  },
  {
    company: "/assets/images/users/user-4.jpg",
    category: "Sitework & Site Utilities",
    views: 468,
    revenue: "$475.63",
    sales: 114,
    up: false,
  },
  {
    company: "/assets/images/users/user-5.jpg",
    category: "Framing (Steel)",
    views: 357,
    revenue: "$415.37",
    sales: 163,
    up: false,
  },
  {
    company: "/assets/images/users/user-6.jpg",
    category: "Waterproofing & Caulking",
    views: 487,
    revenue: "$436.53",
    sales: 170,
    up: false,
  },
  {
    company: "/assets/images/users/user-1.jpg",
    category: "Site Furnishings",
    views: 357,
    revenue: "$147.36",
    sales: 71,
    up: false,
  },
  {
    company: "/assets/images/users/user-2.jpg",
    category: "Casework",
    views: 465,
    revenue: "$121.67",
    sales: 78,
    up: false,
  },
  {
    company: "/assets/images/users/user-3.jpg",
    category: "Ornamental Railings",
    views: 438,
    revenue: "$213.25",
    sales: 155,
    up: false,
  },
  {
    company: "/assets/images/users/user-4.jpg",
    category: "Waterproofing & Caulking",
    views: 461,
    revenue: "$186.48",
    sales: 137,
    up: false,
  },
  {
    company: "/assets/images/users/user-5.jpg",
    category: "Masonry",
    views: 423,
    revenue: "$130.97",
    sales: 178,
    up: false,
  },
  {
    company: "/assets/images/users/user-6.jpg",
    category: "Curb & Gutter",
    views: 339,
    revenue: "$255.69",
    sales: 101,
    up: false,
  },
  {
    company: "/assets/images/users/user-1.jpg",
    category: "HVAC",
    views: 361,
    revenue: "$484.64",
    sales: 175,
    up: true,
  },
  {
    company: "/assets/images/users/user-2.jpg",
    category: "Exterior Signage",
    views: 353,
    revenue: "$485.51",
    sales: 176,
    up: true,
  },
  {
    company: "/assets/images/users/user-3.jpg",
    category: "Fire Protection",
    views: 364,
    revenue: "$449.45",
    sales: 136,
    up: true,
  },
  {
    company: "/assets/images/users/user-4.jpg",
    category: "Rebar & Wire Mesh Install",
    views: 493,
    revenue: "$309.61",
    sales: 163,
    up: true,
  },
  {
    company: "/assets/images/users/user-5.jpg",
    category: "Temp Fencing, Decorative Fencing and Gates",
    views: 393,
    revenue: "$372.45",
    sales: 180,
    up: true,
  },
  {
    company: "/assets/images/users/user-6.jpg",
    category: "Fire Protection",
    views: 441,
    revenue: "$470.34",
    sales: 104,
    up: false,
  },
];

export const recentOrder = [
  {
    user: {
      name: "Esther Howard",
      image: "/assets/images/users/user-1.jpg",
    },
    product: "Headphone",
    invoice: "#324567",
    price: "$90.99",
    status: "paid",
  },
  {
    user: {
      name: "Guy Hawkins",
      image: "/assets/images/users/user-2.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$78.65",
    status: "due",
  },
  {
    user: {
      name: "Bessie Cooper",
      image: "/assets/images/users/user-3.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$78.65",
    status: "pending",
  },
  {
    user: {
      name: "Kathryn Murphy",
      image: "/assets/images/users/user-4.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$38.65",
    status: "cancled",
  },
  {
    user: {
      name: "Darrell Steward",
      image: "/assets/images/users/user-5.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$178.65",
    status: "shipped",
  },
  {
    user: {
      name: "Darrell Steward",
      image: "/assets/images/users/user-6.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$74.65",
    status: "cancled",
  },
  {
    user: {
      name: "Esther Howard",
      image: "/assets/images/users/user-1.jpg",
    },
    product: "Headphone",
    invoice: "#324567",
    price: "$90.99",
    status: "paid",
  },
  {
    user: {
      name: "Guy Hawkins",
      image: "/assets/images/users/user-2.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$78.65",
    status: "due",
  },
  {
    user: {
      name: "Bessie Cooper",
      image: "/assets/images/users/user-3.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$78.65",
    status: "pending",
  },
  {
    user: {
      name: "Kathryn Murphy",
      image: "/assets/images/users/user-4.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$38.65",
    status: "cancled",
  },
  {
    user: {
      name: "Darrell Steward",
      image: "/assets/images/users/user-5.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$178.65",
    status: "shipped",
  },
  {
    user: {
      name: "Darrell Steward",
      image: "/assets/images/users/user-6.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$74.65",
    status: "cancled",
  },
  {
    user: {
      name: "Esther Howard",
      image: "/assets/images/users/user-1.jpg",
    },
    product: "Headphone",
    invoice: "#324567",
    price: "$90.99",
    status: "paid",
  },
  {
    user: {
      name: "Guy Hawkins",
      image: "/assets/images/users/user-2.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$78.65",
    status: "due",
  },
  {
    user: {
      name: "Bessie Cooper",
      image: "/assets/images/users/user-3.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$78.65",
    status: "pending",
  },
  {
    user: {
      name: "Kathryn Murphy",
      image: "/assets/images/users/user-4.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$38.65",
    status: "cancled",
  },
  {
    user: {
      name: "Darrell Steward",
      image: "/assets/images/users/user-5.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$178.65",
    status: "shipped",
  },
  {
    user: {
      name: "Darrell Steward",
      image: "/assets/images/users/user-6.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$74.65",
    status: "cancled",
  },
  {
    user: {
      name: "Esther Howard",
      image: "/assets/images/users/user-1.jpg",
    },
    product: "Headphone",
    invoice: "#324567",
    price: "$90.99",
    status: "paid",
  },
  {
    user: {
      name: "Guy Hawkins",
      image: "/assets/images/users/user-2.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$78.65",
    status: "due",
  },
  {
    user: {
      name: "Bessie Cooper",
      image: "/assets/images/users/user-3.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$78.65",
    status: "pending",
  },
  {
    user: {
      name: "Kathryn Murphy",
      image: "/assets/images/users/user-4.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$38.65",
    status: "cancled",
  },
  {
    user: {
      name: "Darrell Steward",
      image: "/assets/images/users/user-5.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$178.65",
    status: "shipped",
  },
  {
    user: {
      name: "Darrell Steward",
      image: "/assets/images/users/user-6.jpg",
    },
    product: "Headphone",
    invoice: "#4224",
    price: "$74.65",
    status: "cancled",
  },
];

export const teamData = [
  {
    customer: {
      name: "Arlene McCoy",
      image: "/assets/images/users/user-1.jpg",
      deg: "Ux designer",
    },
    status: "progress",
    time: "42.5 hours",
    chart: null,
  },
  {
    customer: {
      name: "Arlene McCoy",
      image: "/assets/images/users/user-2.jpg",
      deg: "Ux designer",
    },
    status: "complete",
    time: "42.5 hours",
    chart: null,
  },
  {
    customer: {
      name: "Arlene McCoy",
      image: "/assets/images/users/user-3.jpg",
      deg: "Ux designer",
    },
    status: "progress",
    time: "42.5 hours",
    chart: null,
  },
  {
    customer: {
      name: "Arlene McCoy",
      image: "/assets/images/users/user-4.jpg",
      deg: "Ux designer",
    },
    status: "complete",
    time: "42.5 hours",
    chart: null,
  },
];








